# -*- coding: utf-8 -*-
"""LSTM(with speech dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcnaPCcuxudPfGm8ihAVXJcIN_F2Xt9P
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Load dataset
df = pd.read_csv("/content/pd_speech_features.csv")
df.head()

# Check the unique values in the target column
print(df['class'].unique())

print(df.columns)

print(df['class'].value_counts())

df = df.drop(columns=['id', 'gender'])  # Removing categorical data

# Check for missing values
print(df.isnull().sum())

# Fill missing values with median (better for skewed data)
df.fillna(df.median(), inplace=True)

df.describe()

# Define features (X) and labels (y)
X = df.drop(columns=['class'])  # Assuming 'class' is the target
y = df['class']

 # Normalize Features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# Reshape for LSTM (samples, time steps, features)
X_reshaped = X_scaled.reshape(X_scaled.shape[0], 1, X_scaled.shape[1])

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y, test_size=0.2, random_state=42)

print(f"Training Samples: {X_train.shape[0]}, Testing Samples: {X_test.shape[0]}")

from sklearn.utils.class_weight import compute_class_weight
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve, auc, log_loss
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Load dataset
df = pd.read_csv("/content/pd_speech_features.csv")
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['class'])
X = df.drop(['class'], axis=1)

# Standardize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Reshape for LSTM
X = X.reshape(X.shape[0], 1, X.shape[1])

def build_lstm_model(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=45)

# Trackers
fold_train_accs = []
fold_test_accs = []
fold_train_losses = []
fold_test_losses = []
roc_probs = []
roc_labels = []

for fold, (train_idx, test_idx) in enumerate(kf.split(X, y)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    model = build_lstm_model(input_shape=(X_train.shape[1], X_train.shape[2]))
    history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=30, batch_size=32, verbose=0)

    # Final Training Evaluation
    y_pred_train = (model.predict(X_train) > 0.5).astype(int)
    y_pred_test = (model.predict(X_test) > 0.5).astype(int)
    y_prob_test = model.predict(X_test).ravel()

    train_acc_fold = accuracy_score(y_train, y_pred_train)
    test_acc_fold = accuracy_score(y_test, y_pred_test)

    train_loss_fold = log_loss(y_train, model.predict(X_train).ravel())
    test_loss_fold = log_loss(y_test, y_prob_test)

    fold_train_accs.append(train_acc_fold)
    fold_test_accs.append(test_acc_fold)
    fold_train_losses.append(train_loss_fold)
    fold_test_losses.append(test_loss_fold)

    roc_probs.extend(y_prob_test)
    roc_labels.extend(y_test)

# ----------------------------------------
# 📈 Accuracy per Fold
plt.figure(figsize=(8,5))
plt.plot(range(1, len(fold_train_accs)+1), fold_train_accs, marker='o', linestyle='-', label='Train Accuracy', color='blue')
plt.plot(range(1, len(fold_test_accs)+1), fold_test_accs, marker='s', linestyle='-', label='Test Accuracy', color='orange')
plt.xlabel('Fold')
plt.ylabel('Accuracy')
plt.title('Training and Testing Accuracy per Fold (LSTM)')
plt.legend()
plt.grid(True)
plt.show()

# ----------------------------------------
# 📈 Loss per Fold
plt.figure(figsize=(8,5))
plt.plot(range(1, len(fold_train_losses)+1), fold_train_losses, marker='o', linestyle='-', label='Train Loss', color='green')
plt.plot(range(1, len(fold_test_losses)+1), fold_test_losses, marker='s', linestyle='-', label='Test Loss', color='red')
plt.xlabel('Fold')
plt.ylabel('Loss')
plt.title('Training and Testing Loss per Fold (LSTM)')
plt.legend()
plt.grid(True)
plt.show()

# ----------------------------------------
# 📈 Single ROC Curve
fpr, tpr, _ = roc_curve(roc_labels, roc_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}', color='darkorange')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Average Across All Folds)')
plt.legend()
plt.grid(True)
plt.show()

# ----------------------------------------
# 📋 Print Averages
print(f"\n📊 Average Train Accuracy: {np.mean(fold_train_accs):.4f}")
print(f"📊 Average Test Accuracy: {np.mean(fold_test_accs):.4f}")
print(f"📊 Average Train Loss: {np.mean(fold_train_losses):.4f}")
print(f"📊 Average Test Loss: {np.mean(fold_test_losses):.4f}")
print(f"📊 Overall AUC: {roc_auc:.4f}")

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Predict on Test Data
y_pred = (model.predict(X_test) > 0.6).astype("int32")

# Print Classification Report
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["Healthy", "Parkinson’s"], yticklabels=["Healthy", "Parkinson’s"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, log_loss
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Load dataset
df = pd.read_csv("/content/pd_speech_features.csv")
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['class'])
X = df.drop(['class'], axis=1)

# Standardize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Reshape for LSTM
X = X.reshape(X.shape[0], 1, X.shape[1])

def build_lstm_model(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=45)

# Trackers
fold_train_accs = []
fold_train_losses = []

for fold, (train_idx, test_idx) in enumerate(kf.split(X, y)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    model = build_lstm_model(input_shape=(X_train.shape[1], X_train.shape[2]))
    model.fit(X_train, y_train, epochs=30, batch_size=32, verbose=0)

    # Evaluate on training set only
    y_pred_train = (model.predict(X_train) > 0.5).astype(int)
    y_prob_train = model.predict(X_train).ravel()

    train_acc_fold = accuracy_score(y_train, y_pred_train)
    train_loss_fold = log_loss(y_train, y_prob_train)

    fold_train_accs.append(train_acc_fold)
    fold_train_losses.append(train_loss_fold)

# ----------------------------------------
# 📈 Training Accuracy per Fold
plt.figure(figsize=(8,5))
plt.plot(range(1, len(fold_train_accs)+1), fold_train_accs, marker='o', linestyle='-', color='green')
plt.xlabel('Fold')
plt.ylabel('Training Accuracy')
plt.title('Training Accuracy per Fold (LSTM)')
plt.grid(True)
plt.show()

# ----------------------------------------
# 📈 Training Loss per Fold
plt.figure(figsize=(8,5))
plt.plot(range(1, len(fold_train_losses)+1), fold_train_losses, marker='s', linestyle='-', color='red')
plt.xlabel('Fold')
plt.ylabel('Training Loss')
plt.title('Training Loss per Fold (LSTM)')
plt.grid(True)
plt.show()

# ----------------------------------------
# 📋 Print Averages
print(f"\n📊 Average Training Accuracy: {np.mean(fold_train_accs):.4f}")
print(f"📊 Average Training Loss: {np.mean(fold_train_losses):.4f}")

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc, log_loss
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Load dataset
df = pd.read_csv("/content/pd_speech_features.csv")
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['class'])
X = df.drop(['class'], axis=1)

# Standardize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Reshape for LSTM
X = X.reshape(X.shape[0], 1, X.shape[1])

def build_lstm_model(input_shape):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=45)

# Trackers
train_accs = []          # Training accuracy per epoch
train_losses = []        # Training loss per epoch
fold_train_accs = []     # Training accuracy after each fold
fold_test_accs = []      # Testing accuracy after each fold
acc_scores = []          # Accuracy on test per fold
precision_scores = []    # Precision per fold
recall_scores = []       # Recall per fold
f1_scores = []           # F1 per fold
roc_probs = []           # Probabilities for ROC
roc_labels = []          # True labels for ROC

for fold, (train_idx, test_idx) in enumerate(kf.split(X, y)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    model = build_lstm_model(input_shape=(X_train.shape[1], X_train.shape[2]))
    history = model.fit(X_train, y_train, epochs=30, batch_size=32, verbose=0)

    # Collect training acc/loss per epoch
    train_accs.extend(history.history['accuracy'])
    train_losses.extend(history.history['loss'])

    # Final fold evaluation
    y_pred_train = (model.predict(X_train) > 0.5).astype(int)
    y_pred_test = (model.predict(X_test) > 0.5).astype(int)
    y_prob_test = model.predict(X_test).ravel()

    train_acc_fold = accuracy_score(y_train, y_pred_train)
    test_acc_fold = accuracy_score(y_test, y_pred_test)

    fold_train_accs.append(train_acc_fold)
    fold_test_accs.append(test_acc_fold)

    acc_scores.append(test_acc_fold)
    precision_scores.append(precision_score(y_test, y_pred_test))
    recall_scores.append(recall_score(y_test, y_pred_test))
    f1_scores.append(f1_score(y_test, y_pred_test))

    roc_probs.extend(y_prob_test)
    roc_labels.extend(y_test)

# ==============================================
# 📈 Training Accuracy per Epoch
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', linestyle='-', color='green')
plt.xlabel('Epoch')
plt.ylabel('Training Accuracy')
plt.title('Training Accuracy per Epoch (LSTM)')
plt.grid(True)
plt.show()

# 📈 Training Loss per Epoch
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', linestyle='-', color='red')
plt.xlabel('Epoch')
plt.ylabel('Training Loss')
plt.title('Training Loss per Epoch (LSTM)')
plt.grid(True)
plt.show()

# 📈 Train vs Test Accuracy per Fold
plt.figure(figsize=(8,5))
plt.plot(range(1, len(fold_train_accs)+1), fold_train_accs, marker='o', linestyle='-', label='Train Accuracy', color='blue')
plt.plot(range(1, len(fold_test_accs)+1), fold_test_accs, marker='s', linestyle='-', label='Test Accuracy', color='orange')
plt.xlabel('Fold')
plt.ylabel('Accuracy')
plt.title('Train vs Test Accuracy per Fold (LSTM)')
plt.xticks(range(1, len(fold_train_accs)+1))
plt.legend()
plt.grid(True)
plt.show()

# 📈 Evaluation Metrics (Bar Chart)
metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
avg_metrics = [
    np.mean(acc_scores),
    np.mean(precision_scores),
    np.mean(recall_scores),
    np.mean(f1_scores)
]

plt.figure(figsize=(6,4))
sns.barplot(x=metrics_names, y=avg_metrics, palette='Set2')
plt.ylim(0, 1)
plt.title('Evaluation Metrics (Average Across Folds)')
plt.ylabel('Score')
plt.grid(True)
plt.show()

# 📈 ROC Curve (Average Across Folds)
fpr, tpr, _ = roc_curve(roc_labels, roc_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}', color='darkorange')
plt.plot([0, 1], [0, 1], 'k--', color='navy', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Average Across Folds)')
plt.legend()
plt.grid(True)
plt.show()

# 📋 Print Final Metrics
print(f"\n📊 Average Train Accuracy: {np.mean(fold_train_accs):.4f}")
print(f"📊 Average Test Accuracy: {np.mean(fold_test_accs):.4f}")
print(f"📊 Overall AUC: {roc_auc:.4f}")