# -*- coding: utf-8 -*-
"""ML_Models(on speech dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQhWTx0JLzirMo1I8R9-HiQNC0iFD8tn
"""

# 1. Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

# 2. Load Dataset
df = pd.read_csv("/content/pd_speech_features.csv")

# 3. Preprocessing
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['class'])
X = df.drop(['class'], axis=1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# 4. Define Models
models = {
    "SVM": SVC(kernel='sigmoid', probability=True, random_state=0),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=0)
}

# 5. Cross-validation setup
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, roc_curve, auc
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Assuming X_train, y_train, X_test, y_test already exist

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)

models = {
    "SVM": SVC(kernel='sigmoid', probability=True, random_state=0),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=0)
}

# Part 1: Plot Accuracy per Fold (for all models)
for model_name, model in models.items():
    print(f"\n=== {model_name} ===")

    train_accs = []
    test_accs = []

    for train_index, val_index in kf.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train[train_index], X_train[val_index]
        y_fold_train, y_fold_val = y_train[train_index], y_train[val_index]

        model_fold = clone(model)
        model_fold.fit(X_fold_train, y_fold_train)

        y_train_pred = model_fold.predict(X_fold_train)
        y_val_pred = model_fold.predict(X_fold_val)

        train_acc = accuracy_score(y_fold_train, y_train_pred)
        val_acc = accuracy_score(y_fold_val, y_val_pred)

        train_accs.append(train_acc)
        test_accs.append(val_acc)

    # Plot Train vs Test Accuracy per Fold
    plt.figure(figsize=(8,5))
    plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', label='Train Accuracy', color='blue')
    plt.plot(range(1, len(test_accs)+1), test_accs, marker='s', label='Test Accuracy', color='orange')
    plt.xlabel('Fold')
    plt.ylabel('Accuracy')
    plt.title(f'{model_name} - Train vs Test Accuracy per Fold')
    plt.legend()
    plt.grid(True)
    plt.show()

# ==========================================================

# Part 2: Special Random Forest Training (Train Acc/Loss per Epoch with warm_start)
print("\n=== Random Forest (Accuracy & Loss per Epoch) ===")

rf = RandomForestClassifier(n_estimators=1, warm_start=True, random_state=42)

# Tracking lists
train_accuracies = []
test_accuracies = []
train_losses = []
test_losses = []

n_estimators_max = 100  # Number of trees

for epoch in range(1, n_estimators_max + 1):
    rf.set_params(n_estimators=epoch)
    rf.fit(X_train, y_train)

    # Train evaluation
    y_train_pred = rf.predict(X_train)
    y_train_prob = rf.predict_proba(X_train)
    train_acc = accuracy_score(y_train, y_train_pred)
    train_loss = log_loss(y_train, y_train_prob)

    # Test evaluation
    y_test_pred = rf.predict(X_test)
    y_test_prob = rf.predict_proba(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)
    test_loss = log_loss(y_test, y_test_prob)

    # Save metrics
    train_accuracies.append(train_acc)
    test_accuracies.append(test_acc)
    train_losses.append(train_loss)
    test_losses.append(test_loss)

# --- Plot ONLY Training Accuracy per Epoch ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accuracies)+1), train_accuracies, marker='o', linestyle='-', color='green')
plt.xlabel('Epoch (Number of Trees)')
plt.ylabel('Training Accuracy')
plt.title('Random Forest - Training Accuracy per Epoch')
plt.grid(True)
plt.show()

# --- Plot ONLY Training Loss per Epoch ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', linestyle='-', color='red')
plt.xlabel('Epoch (Number of Trees)')
plt.ylabel('Training Loss')
plt.title('Random Forest - Training Loss per Epoch')
plt.grid(True)
plt.show()

from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, log_loss
import matplotlib.pyplot as plt

kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

print("\n=== SVM ===")

train_accs = []
train_losses = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X_train, y_train)):
    print(f"\nFold {fold+1}")

    X_fold_train, X_fold_val = X_train[train_idx], X_train[val_idx]
    y_fold_train, y_fold_val = y_train[train_idx], y_train[val_idx]

    svm = SVC(kernel='rbf', probability=True, C=1.0, gamma='scale', random_state=42)
    svm.fit(X_fold_train, y_fold_train)

    # Train evaluation
    y_train_pred = svm.predict(X_fold_train)
    y_train_prob = svm.predict_proba(X_fold_train)[:, 1]

    train_acc = accuracy_score(y_fold_train, y_train_pred)
    train_loss = log_loss(y_fold_train, svm.predict_proba(X_fold_train))

    train_accs.append(train_acc)
    train_losses.append(train_loss)

    print(f"Train Accuracy: {train_acc:.4f} | Train Loss: {train_loss:.4f}")

# --- Plot Train Accuracy per Fold (Epoch) ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', color='green')
plt.xlabel('Epoch (Fold)')
plt.ylabel('Training Accuracy')
plt.title('SVM - Training Accuracy per Epoch')
plt.grid(True)
plt.show()

# --- Plot Train Loss per Fold (Epoch) ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', color='blue')
plt.xlabel('Epoch (Fold)')
plt.ylabel('Training Loss')
plt.title('SVM - Training Loss per Epoch')
plt.grid(True)
plt.show()

from sklearn.base import clone
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, log_loss

# 6. Training and plotting per model
for model_name, model in models.items():
    print(f"\n=== {model_name} ===")

    # Initialize lists
    train_accs = []
    test_accs = []
    train_losses = []
    test_losses = []
    fold_metrics = []

    if model_name == "KNN":
        # Special handling for KNN: fold-by-fold = epoch-by-epoch
        for epoch, (train_idx, val_idx) in enumerate(kf.split(X_train, y_train)):
            X_fold_train, X_fold_val = X_train[train_idx], X_train[val_idx]
            y_fold_train, y_fold_val = y_train[train_idx], y_train[val_idx]

            model_fold = clone(model)
            model_fold.fit(X_fold_train, y_fold_train)

            # Train predictions
            y_train_pred = model_fold.predict(X_fold_train)
            y_train_prob = model_fold.predict_proba(X_fold_train)[:, 1]

            train_acc = accuracy_score(y_fold_train, y_train_pred)
            train_loss = log_loss(y_fold_train, model_fold.predict_proba(X_fold_train))

            # Test predictions
            y_val_pred = model_fold.predict(X_fold_val)
            y_val_prob = model_fold.predict_proba(X_fold_val)[:, 1]

            val_acc = accuracy_score(y_fold_val, y_val_pred)
            val_loss = log_loss(y_fold_val, model_fold.predict_proba(X_fold_val))

            train_accs.append(train_acc)
            test_accs.append(val_acc)
            train_losses.append(train_loss)
            test_losses.append(val_loss)

            print(f"Epoch {epoch+1}: Train Acc={train_acc:.4f}, Val Acc={val_acc:.4f}, "
                  f"Train Loss={train_loss:.4f}, Val Loss={val_loss:.4f}")

        # After all folds (epochs)
        # Plot Accuracy per Epoch
        plt.figure(figsize=(8,5))
        plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', label='Train Accuracy', color='blue')
        plt.plot(range(1, len(test_accs)+1), test_accs, marker='s', label='Validation Accuracy', color='orange')
        plt.xlabel('Epoch (Fold)')
        plt.ylabel('Accuracy')
        plt.title(f'{model_name} - Accuracy per Epoch')
        plt.legend()
        plt.grid(True)
        plt.show()

        # Plot Loss per Epoch
        plt.figure(figsize=(8,5))
        plt.plot(range(1, len(train_losses)+1), train_losses, marker='o', label='Train Loss', color='green')
        plt.plot(range(1, len(test_losses)+1), test_losses, marker='s', label='Validation Loss', color='red')
        plt.xlabel('Epoch (Fold)')
        plt.ylabel('Loss')
        plt.title(f'{model_name} - Loss per Epoch')
        plt.legend()
        plt.grid(True)
        plt.show()

    else:
        # Normal processing for SVM and Random Forest
        acc_scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='accuracy')
        avg_acc = np.mean(acc_scores)
        std_acc = np.std(acc_scores)
        print(f"Average CV Accuracy: {avg_acc:.4f} ± {std_acc:.4f}")

        model.fit(X_train, y_train)

        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        y_prob_test = model.predict_proba(X_test)[:, 1]

        train_acc = accuracy_score(y_train, y_pred_train)
        test_acc = accuracy_score(y_test, y_pred_test)

        print(f"Train Accuracy: {train_acc:.4f}")
        print(f"Test Accuracy: {test_acc:.4f}")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

for model_name, model in models.items():
    print(f"\n=== {model_name} ===")

    # Initialize lists to store per-fold accuracies
    train_accs = []
    test_accs = []

    # Cross-validation loop
    for train_index, val_index in kf.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train[train_index], X_train[val_index]
        y_fold_train, y_fold_val = y_train[train_index], y_train[val_index]

        model_fold = clone(model)
        model_fold.fit(X_fold_train, y_fold_train)

        y_train_pred = model_fold.predict(X_fold_train)
        y_val_pred = model_fold.predict(X_fold_val)

        train_acc = accuracy_score(y_fold_train, y_train_pred)
        val_acc = accuracy_score(y_fold_val, y_val_pred)

        train_accs.append(train_acc)
        test_accs.append(val_acc)

    # Full model training
    model.fit(X_train, y_train)
    y_pred_test = model.predict(X_test)
    y_prob_test = model.predict_proba(X_test)[:, 1]

    # === Evaluation Metrics ===
    acc = accuracy_score(y_test, y_pred_test)
    prec = precision_score(y_test, y_pred_test)
    rec = recall_score(y_test, y_pred_test)
    f1 = f1_score(y_test, y_pred_test)

    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1 Score:  {f1:.4f}")

    # --- Optionally plot metrics ---
    metrics = [acc, prec, rec, f1]
    metric_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']

    plt.figure(figsize=(6,4))
    sns.barplot(x=metric_names, y=metrics, palette='Set2')
    plt.ylim(0, 1)
    plt.title(f"{model_name} Evaluation Metrics")
    plt.ylabel('Score')
    plt.show()

from sklearn.metrics import roc_curve, auc

# First fit and predict probabilities
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train, y_train)

    # Check if model supports predict_proba
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For models like SVM, if needed
        y_prob = model.decision_function(X_test)
        y_prob = (y_prob - y_prob.min()) / (y_prob.max() - y_prob.min())  # Normalize to [0,1]

    # Compute ROC curve and AUC
    fpr, tpr, thresholds = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    # Now plot separate ROC curve for each model
    plt.figure(figsize=(7,5))
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'ROC Curve - {model_name}')
    plt.legend(loc="lower right")
    plt.grid(True)
    plt.show()