# -*- coding: utf-8 -*-
"""ANN(clinical dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJtuXWwpUNeZvWgXM-YCEMyfd7_vN1AS
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, log_loss, confusion_matrix, roc_curve, auc

import warnings
warnings.filterwarnings('ignore')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load clinical dataset
clinical_df = pd.read_csv("/content/parkinsons_disease_data.csv").dropna()

# Drop irrelevant columns
clinical_df = clinical_df.drop(columns=['PatientID', 'DoctorInCharge'], errors='ignore')

# Extract labels
y = clinical_df['Diagnosis'].values

# Prepare feature matrix
X = clinical_df.drop(columns=['Diagnosis'])

# One-hot encode categorical features
X = pd.get_dummies(X, drop_first=True)

# Impute missing values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

print("Data preprocessing complete!")
print("X shape:", X_scaled.shape)
print("y shape:", y.shape)

# Prepare tensors
X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)

class ANN(nn.Module):
    def __init__(self, input_size):
        super(ANN, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 2)
        )

    def forward(self, x):
        return self.model(x)

# Define Stratified K-Fold
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Track metrics for all folds
fold_metrics = []
train_accs = []
test_accs = []
train_losses = []
test_losses = []

EPOCHS = 20
BATCH_SIZE = 32

for fold, (train_idx, test_idx) in enumerate(kfold.split(X_tensor, y_tensor)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, X_test = X_tensor[train_idx], X_tensor[test_idx]
    y_train, y_test = y_tensor[train_idx], y_tensor[test_idx]

    # Model
    model = ANN(input_size=X_tensor.shape[1]).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    # Training
    model.train()
    for epoch in range(EPOCHS):
        idx = torch.randperm(len(X_train))
        X_train, y_train = X_train[idx], y_train[idx]

        total_loss = 0
        for i in range(0, len(X_train), BATCH_SIZE):
            xb = X_train[i:i+BATCH_SIZE].to(device)
            yb = y_train[i:i+BATCH_SIZE].to(device)

            logits = model(xb)
            loss = criterion(logits, yb)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

    # Evaluation
    model.eval()
    with torch.no_grad():
        y_train_logits = model(X_train.to(device))
        y_train_pred = torch.argmax(y_train_logits, dim=1).cpu().numpy()
        y_train_probs = torch.softmax(y_train_logits, dim=1)[:, 1].cpu().numpy()

        y_test_logits = model(X_test.to(device))
        y_test_pred = torch.argmax(y_test_logits, dim=1).cpu().numpy()
        y_test_probs = torch.softmax(y_test_logits, dim=1)[:, 1].cpu().numpy()

    # Metrics
    train_acc = accuracy_score(y_train.numpy(), y_train_pred)
    train_loss = log_loss(y_train.numpy(), np.vstack((1-y_train_probs, y_train_probs)).T)

    test_acc = accuracy_score(y_test.numpy(), y_test_pred)
    test_loss = log_loss(y_test.numpy(), np.vstack((1-y_test_probs, y_test_probs)).T)

    f1 = f1_score(y_test.numpy(), y_test_pred)
    auc_score = roc_auc_score(y_test.numpy(), y_test_probs)
    precision = precision_score(y_test.numpy(), y_test_pred)
    recall = recall_score(y_test.numpy(), y_test_pred)

    train_accs.append(train_acc)
    test_accs.append(test_acc)
    train_losses.append(train_loss)
    test_losses.append(test_loss)

    fold_metrics.append((train_acc, test_acc, f1, auc_score, precision, recall, train_loss, test_loss))

    print(f"Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f} | F1: {f1:.4f} | "
          f"AUC: {auc_score:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f} | "
          f"Train Loss: {train_loss:.4f} | Test Loss: {test_loss:.4f}")

# Average results
metrics_avg = np.mean(fold_metrics, axis=0)
print("\n📊 Average across folds:")
print(f"Train Accuracy: {metrics_avg[0]:.4f}")
print(f"Test Accuracy: {metrics_avg[1]:.4f}")
print(f"F1 Score: {metrics_avg[2]:.4f}")
print(f"AUC: {metrics_avg[3]:.4f}")
print(f"Precision: {metrics_avg[4]:.4f}")
print(f"Recall: {metrics_avg[5]:.4f}")
print(f"Train Loss: {metrics_avg[6]:.4f}")
print(f"Test Loss: {metrics_avg[7]:.4f}")

# After evaluating
metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
metrics_values = [test_acc, precision, recall, f1]

plt.figure(figsize=(6,5))
sns.barplot(x=metrics_names, y=metrics_values, palette="viridis")
plt.ylim(0,1)
plt.title('Evaluation Metrics')
for index, value in enumerate(metrics_values):
    plt.text(index, value + 0.02, f"{value:.2f}", ha='center')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', label='Train Accuracy', color='blue')
plt.plot(range(1, len(test_accs)+1), test_accs, marker='s', label='Test Accuracy', color='orange')
plt.xlabel('Fold')
plt.ylabel('Accuracy')
plt.title('Train vs Test Accuracy per Fold')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', color='green')
plt.xlabel('Epoch')
plt.ylabel('Training Accuracy')
plt.title('Training Accuracy per Epoch')
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', color='red')
plt.xlabel('Epoch')
plt.ylabel('Training Loss')
plt.title('Training Loss per Epoch')
plt.grid(True)
plt.show()

fpr, tpr, thresholds = roc_curve(y_test, y_test_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

cm = confusion_matrix(y_test, y_test_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()