# -*- coding: utf-8 -*-
"""LSTM (with clinical data).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hjyi5C3pf0E6k5YbDw9XMCtYW2Ib3_Ha
"""

import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
import warnings
warnings.filterwarnings("ignore")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Load dataset
df = pd.read_csv("/content/parkinsons_disease_data.csv").dropna()
df = df.drop(columns=['PatientID', 'DoctorInCharge'], errors='ignore')
y = df['Diagnosis'].values

# Feature matrix
X = df.drop(columns=['Diagnosis'])
X = pd.get_dummies(X, drop_first=True)

# Impute missing values
from sklearn.impute import SimpleImputer
feature_names = X.columns
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# 🔥 Feature transformation (NEW)
from sklearn.preprocessing import PowerTransformer
transformer = PowerTransformer(method='yeo-johnson')
X_transformed = transformer.fit_transform(X_imputed)

# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_transformed)

# Feature selection
from sklearn.feature_selection import SelectKBest, f_classif
selector = SelectKBest(score_func=f_classif, k=20)
X_selected = selector.fit_transform(X_scaled, y)

selected_mask = selector.get_support()
selected_features = feature_names[selected_mask]
print("Top selected features:\n", selected_features.tolist())

# Final tensor prep
import torch
X_tensor = torch.tensor(X_selected, dtype=torch.float32).unsqueeze(-1)
y_tensor = torch.tensor(y, dtype=torch.long)

class TabularLSTM(nn.Module):
    def __init__(self, input_size=35, hidden_size=64, num_layers=2, bidirectional=True):
        super(TabularLSTM, self).__init__()

        self.hidden_size = hidden_size
        self.num_directions = 2 if bidirectional else 1

        self.lstm = nn.LSTM(
            input_size,
            hidden_size,
            num_layers,
            batch_first=True,
            bidirectional=bidirectional
        )

        self.dropout = nn.Dropout(0.3)
        self.relu = nn.ReLU()
        self.fc = nn.Linear(hidden_size * self.num_directions, 2)

    def forward(self, x):
        _, (hn, _) = self.lstm(x)
        hn = hn[-self.num_directions:]

        hn = hn.transpose(0, 1).contiguous().view(x.size(0), -1)

        out = self.dropout(hn)
        out = self.relu(out)
        out = self.fc(out)

        return out

EPOCHS = 15
BATCH_SIZE = 16
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

train_accs = []
test_accs = []
train_losses = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_tensor, y_tensor)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, y_train = X_tensor[train_idx], y_tensor[train_idx]
    X_val, y_val = X_tensor[val_idx], y_tensor[val_idx]

    model = TabularLSTM(input_size=1).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)
    # optimizer = torch.optim.SGD(model.parameters(), lr=1e-1, momentum=0.9)

    for epoch in range(EPOCHS):
        model.train()
        idx = torch.randperm(len(X_train))
        X_train, y_train = X_train[idx], y_train[idx]

        epoch_loss = 0.0
        all_preds, all_labels, all_probs = [], [], []

        for i in range(0, len(X_train), BATCH_SIZE):
            xb = X_train[i:i+BATCH_SIZE].to(device)
            yb = y_train[i:i+BATCH_SIZE].to(device)

            logits = model(xb)
            loss = criterion(logits, yb)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            preds = torch.argmax(logits, dim=1)
            probs = torch.softmax(logits, dim=1)[:, 1]

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.detach().cpu().numpy())
            all_labels.extend(yb.cpu().numpy())
            epoch_loss += loss.item()

        avg_epoch_loss = epoch_loss / (len(X_train) // BATCH_SIZE)

        train_acc = accuracy_score(all_labels, all_preds)
        train_f1 = f1_score(all_labels, all_preds)
        train_auc = roc_auc_score(all_labels, all_probs)
        train_precision = precision_score(all_labels, all_preds)
        train_recall = recall_score(all_labels, all_preds)

        # === Validation ===
        model.eval()
        with torch.no_grad():
            val_logits = model(X_val.to(device))
            val_preds = torch.argmax(val_logits, dim=1).cpu().numpy()
            val_probs = torch.softmax(val_logits, dim=1)[:, 1].cpu().numpy()
            val_labels = y_val.numpy()

        val_acc = accuracy_score(val_labels, val_preds)
        val_f1 = f1_score(val_labels, val_preds)
        val_auc = roc_auc_score(val_labels, val_probs)
        val_precision = precision_score(val_labels, val_preds)
        val_recall = recall_score(val_labels, val_preds)

        train_accs.append(train_acc)
        test_accs.append(val_acc)
        train_losses.append(avg_epoch_loss)

        print(f"Epoch {epoch+1:02d}/{EPOCHS} | Loss: {avg_epoch_loss:.4f} | "
              f"Train Acc: {train_acc:.4f} | F1: {train_f1:.4f} | AUC: {train_auc:.4f} | "
              f"Val Acc: {val_acc:.4f} | Val F1: {val_f1:.4f} | Val AUC: {val_auc:.4f} | "
              f"Precision: {val_precision:.4f} | Recall: {val_recall:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, label='Train Accuracy', marker='o')
plt.plot(range(1, len(test_accs)+1), test_accs, label='Test Accuracy', marker='s')
plt.xlabel('Fold')
plt.ylabel('Accuracy')
plt.title('Train vs Test Accuracy per Fold')
plt.legend()
plt.grid(True)
plt.show()

fpr, tpr, thresholds = roc_curve(y_val, val_preds)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

# After evaluating
metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
metrics_values = [val_acc, val_precision, val_recall, val_f1]

plt.figure(figsize=(6,5))
sns.barplot(x=metrics_names, y=metrics_values, palette="viridis")
plt.ylim(0,1)
plt.title('Evaluation Metrics')
for index, value in enumerate(metrics_values):
    plt.text(index, value + 0.02, f"{value:.2f}", ha='center')
plt.grid(True)
plt.show()

# After test prediction:
cm = confusion_matrix(y_val, val_preds)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

import matplotlib.pyplot as plt

# --- Plot Training Accuracy per Epoch ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', linestyle='-', color='green')
plt.xlabel('Epoch')
plt.ylabel('Training Accuracy')
plt.title('Training Accuracy per Epoch')
plt.grid(True)
plt.show()

# --- Plot Training Loss per Epoch ---
plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', linestyle='-', color='red')
plt.xlabel('Epoch')
plt.ylabel('Training Loss')
plt.title('Training Loss per Epoch')
plt.grid(True)
plt.show()