# -*- coding: utf-8 -*-
"""RF(clinical dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4gB1mJMzbsHmuuXo6z8sxl31OkMpxFI
"""

# Basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn imports
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, log_loss, confusion_matrix, roc_curve, auc

import warnings
warnings.filterwarnings('ignore')

# Load clinical dataset
clinical_df = pd.read_csv("/content/parkinsons_disease_data.csv").dropna()

# Drop irrelevant columns
clinical_df = clinical_df.drop(columns=['PatientID', 'DoctorInCharge'], errors='ignore')

# Extract labels
y = clinical_df['Diagnosis'].values

# Prepare feature matrix
X = clinical_df.drop(columns=['Diagnosis'])

# One-hot encode categorical features
X = pd.get_dummies(X, drop_first=True)

# Impute missing values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

print("Data preprocessing complete!")
print("X shape:", X_scaled.shape)
print("y shape:", y.shape)

# Define Stratified K-Fold
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Track metrics for all folds
fold_metrics = []
train_accs = []
test_accs = []
train_losses = []
test_losses = []

for fold, (train_idx, test_idx) in enumerate(kfold.split(X_scaled, y)):
    print(f"\n========== Fold {fold+1} ==========")

    X_train, X_test = X_scaled[train_idx], X_scaled[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # Initialize Random Forest
    rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)

    # Train
    rf.fit(X_train, y_train)

    # Train set evaluation
    y_train_pred = rf.predict(X_train)
    y_train_prob = rf.predict_proba(X_train)[:, 1]

    train_acc = accuracy_score(y_train, y_train_pred)
    train_loss = log_loss(y_train, rf.predict_proba(X_train))  # Train "loss"

    # Test set evaluation
    y_test_pred = rf.predict(X_test)
    y_test_prob = rf.predict_proba(X_test)[:, 1]

    test_acc = accuracy_score(y_test, y_test_pred)
    test_loss = log_loss(y_test, rf.predict_proba(X_test))  # Test "loss"

    f1 = f1_score(y_test, y_test_pred)
    auc_score = roc_auc_score(y_test, y_test_prob)
    precision = precision_score(y_test, y_test_pred)
    recall = recall_score(y_test, y_test_pred)

    train_accs.append(train_acc)
    test_accs.append(test_acc)
    train_losses.append(train_loss)
    test_losses.append(test_loss)

    fold_metrics.append((train_acc, test_acc, f1, auc_score, precision, recall, train_loss, test_loss))

    print(f"Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f} | F1: {f1:.4f} | "
          f"AUC: {auc_score:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f} | "
          f"Train Loss: {train_loss:.4f} | Test Loss: {test_loss:.4f}")

# Average results
metrics_avg = np.mean(fold_metrics, axis=0)
print("\n📊 Average across folds:")
print(f"Train Accuracy: {metrics_avg[0]:.4f}")
print(f"Test Accuracy: {metrics_avg[1]:.4f}")
print(f"F1 Score: {metrics_avg[2]:.4f}")
print(f"AUC: {metrics_avg[3]:.4f}")
print(f"Precision: {metrics_avg[4]:.4f}")
print(f"Recall: {metrics_avg[5]:.4f}")
print(f"Train Loss: {metrics_avg[6]:.4f}")
print(f"Test Loss: {metrics_avg[7]:.4f}")

# After evaluating
metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
metrics_values = [test_acc, precision, recall, f1]

plt.figure(figsize=(6,5))
sns.barplot(x=metrics_names, y=metrics_values, palette="viridis")
plt.ylim(0,1)
plt.title('Evaluation Metrics')
for index, value in enumerate(metrics_values):
    plt.text(index, value + 0.02, f"{value:.2f}", ha='center')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', label='Train Accuracy', color='blue')
plt.plot(range(1, len(test_accs)+1), test_accs, marker='s', label='Test Accuracy', color='orange')
plt.xlabel('Fold')
plt.ylabel('Accuracy')
plt.title('Train vs Test Accuracy per Fold')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_accs)+1), train_accs, marker='o', color='green')
plt.xlabel('Epoch')
plt.ylabel('Training Accuracy')
plt.title('Training Accuracy per Epoch')
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(range(1, len(train_losses)+1), train_losses, marker='s', color='red')
plt.xlabel('Epoch')
plt.ylabel('Training Loss')
plt.title('Training Loss per Epoch')
plt.grid(True)
plt.show()

fpr, tpr, thresholds = roc_curve(y_test, y_test_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

cm = confusion_matrix(y_test, y_test_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()